name: abet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.2.2
  - pip:
    - matplotlib==3.6.0
    - numpy==1.23.3
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - timm==0.6.11
    - torch==1.11.0
    - torchmetrics==0.11.0
    - torchvision==0.12.0
    - tqdm==4.64.1
    - umap-learn==0.5.3